apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2025-10-31T15:54:16Z"
  generateName: kafka-74dbf87b7b-
  generation: 1
  labels:
    app: kafka
    pod-template-hash: 74dbf87b7b
  name: kafka-74dbf87b7b-tcq4q
  namespace: ecommerce
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: kafka-74dbf87b7b
    uid: 042392f6-6bc1-491e-8622-23055f726e20
  resourceVersion: "11819"
  uid: bf79c7a5-a7e7-4948-86c5-fd4c4173ed84
spec:
  containers:
  - env:
    - name: KAFKA_KRAFT_MODE
      value: "true"
    - name: KAFKA_PROCESS_ROLES
      value: broker,controller
    - name: KAFKA_NODE_ID
      value: "1"
    - name: KAFKA_CONTROLLER_QUORUM_VOTERS
      value: 1@kafka:9093
    - name: KAFKA_LISTENERS
      value: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
    - name: KAFKA_ADVERTISED_LISTENERS
      value: PLAINTEXT://kafka:9092
    - name: KAFKA_INTER_BROKER_LISTENER_NAME
      value: PLAINTEXT
    - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
      value: "true"
    image: confluentinc/cp-kafka:latest
    imagePullPolicy: Always
    name: kafka
    ports:
    - containerPort: 9092
      protocol: TCP
    - containerPort: 9093
      protocol: TCP
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-6mw4z
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: km-5cd3026b2v
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-6mw4z
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2025-11-01T18:02:42Z"
    observedGeneration: 1
    status: "True"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2025-10-31T15:54:16Z"
    observedGeneration: 1
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2025-11-01T17:53:12Z"
    message: 'containers with unready status: [kafka]'
    observedGeneration: 1
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2025-11-01T17:53:12Z"
    message: 'containers with unready status: [kafka]'
    observedGeneration: 1
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2025-10-31T15:54:16Z"
    observedGeneration: 1
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://9469a8f9d3cc73f878dc3b75d4c4731f916c08ad87f1c14a6f02a2cb7bfc2263
    image: confluentinc/cp-kafka:latest
    imageID: docker-pullable://confluentinc/cp-kafka@sha256:9026dbbf280d41868b95ae3995e1fdf0f5db5964776fb9581b52a02e3776d727
    lastState:
      terminated:
        containerID: docker://9469a8f9d3cc73f878dc3b75d4c4731f916c08ad87f1c14a6f02a2cb7bfc2263
        exitCode: 1
        finishedAt: "2025-11-01T18:45:13Z"
        reason: Error
        startedAt: "2025-11-01T18:45:13Z"
    name: kafka
    ready: false
    resources: {}
    restartCount: 25
    started: false
    state:
      waiting:
        message: back-off 5m0s restarting failed container=kafka pod=kafka-74dbf87b7b-tcq4q_ecommerce(bf79c7a5-a7e7-4948-86c5-fd4c4173ed84)
        reason: CrashLoopBackOff
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-6mw4z
      readOnly: true
      recursiveReadOnly: Disabled
  hostIP: 192.168.127.2
  hostIPs:
  - ip: 192.168.127.2
  observedGeneration: 1
  phase: Running
  podIP: 10.42.0.36
  podIPs:
  - ip: 10.42.0.36
  qosClass: BestEffort
  startTime: "2025-10-31T15:54:16Z"
